name: Build and Deploy schoolMoney Backend to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          
      - name: Inject Azure SQL Connection String into appsettings.json
        run: |
          $fileContent = Get-Content -Path "./appsettings.json"
          $fileContent = $fileContent -replace '"AzureSQL": "KEY"', '"AzureSQL": "${{ secrets.AZURE_SQL_CONNECTION_STRING }}"'
          Set-Content -Path "./appsettings.json" -Value $fileContent   

      - name: Inject PasswordKey into appsettings.json
        run: |
          $fileContent = Get-Content -Path "./appsettings.json"
          $fileContent = $fileContent -replace '"PasswordKey": "KEY"', '"PasswordKey": "${{ secrets.PASSWORD_KEY }}"'
          Set-Content -Path "./appsettings.json" -Value $fileContent   

      - name: Inject TokenKey into appsettings.json
        run: |
          $fileContent = Get-Content -Path "./appsettings.json"
          $fileContent = $fileContent -replace '"TokenKey": "KEY"', '"TokenKey": "${{ secrets.TOKEN_KEY }}"'
          Set-Content -Path "./appsettings.json" -Value $fileContent 

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/schoolMoney_backend"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: "${{env.DOTNET_ROOT}}/schoolMoney_backend"

  deploy:
    name: Deploy
    
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_18A37DB9D4C34DF19E7987AC88F99912 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_030BB67EBC0F4BDB9BABFF5D618299C1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1E2262F71902496F8CCEB963F73418AF }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'schoolMoney-backend'
          slot-name: 'Production'
          package: .
          